[build]
  publish = "dist/chatcom"
  command = "npm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Content-Length, User-Agent, x-goog-resumable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 